# Generated by Django 4.0.3 on 2022-03-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0002_listofbooks_auteur_listofbooks_coverbook_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listofbooks',
            name='unique',
        ),
        migrations.AddConstraint(
            model_name='listofbooks',
            constraint=models.UniqueConstraint(fields=('title', 'id', 'auteur'), name='unique'),
        ),
    ]
