# Generated by Django 4.0.3 on 2022-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0003_remove_listofbooks_unique_listofbooks_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listofbooks',
            name='unique',
        ),
        migrations.AddConstraint(
            model_name='listofbooks',
            constraint=models.UniqueConstraint(fields=('title', 'id'), name='unique'),
        ),
    ]
