# Generated by Django 4.0.3 on 2022-03-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0005_remove_listofbooks_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofbooks',
            name='author',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
