# Generated by Django 4.0.3 on 2022-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0006_listofbooks_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofbooks',
            name='author',
            field=models.CharField(max_length=150),
        ),
    ]
