# Generated by Django 4.0.3 on 2022-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0010_listofbooks_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofbooks',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
