# Generated by Django 4.0.3 on 2022-03-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0011_listofbooks_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofbooks',
            name='imageBook',
            field=models.CharField(default='', max_length=355),
        ),
    ]
