# Generated by Django 4.0.3 on 2022-03-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0012_listofbooks_imagebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(default='', max_length=150)),
                ('occurence', models.CharField(default='', max_length=5)),
                ('idBook', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['word', 'idBook'],
            },
        ),
    ]
