# Generated by Django 4.0.3 on 2022-03-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0013_bookindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookindex',
            options={'ordering': ['wordOcc', 'idBook']},
        ),
        migrations.RenameField(
            model_name='bookindex',
            old_name='word',
            new_name='wordOcc',
        ),
        migrations.RemoveField(
            model_name='bookindex',
            name='occurence',
        ),
    ]
