# Generated by Django 4.0.3 on 2022-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0016_alter_bookindex_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookindex',
            options={'ordering': ['id', 'wordOcc']},
        ),
        migrations.RemoveField(
            model_name='bookindex',
            name='idBook',
        ),
        migrations.AlterField(
            model_name='bookindex',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookindex',
            name='wordOcc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
