# Generated by Django 4.0.3 on 2022-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0017_alter_bookindex_options_remove_bookindex_idbook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookindex',
            options={'ordering': ['id', 'title', 'wordOcc']},
        ),
        migrations.AddField(
            model_name='bookindex',
            name='title',
            field=models.CharField(default='', max_length=50000000),
        ),
        migrations.AlterField(
            model_name='bookindex',
            name='wordOcc',
            field=models.CharField(default='', max_length=50000000),
        ),
    ]
