# Generated by Django 4.0.3 on 2022-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0018_alter_bookindex_options_bookindex_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGraphJaccard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idBook', models.CharField(default='', max_length=50000000)),
                ('neighbor', models.CharField(default='', max_length=50000000)),
            ],
            options={
                'ordering': ['id', 'idBook', 'neighbor'],
            },
        ),
    ]
