# Generated by Django 4.0.3 on 2022-03-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0019_bookgraphjaccard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookgraphjaccard',
            options={'ordering': ['id', 'neightbors']},
        ),
        migrations.RenameField(
            model_name='bookgraphjaccard',
            old_name='idBook',
            new_name='neightbors',
        ),
        migrations.RemoveField(
            model_name='bookgraphjaccard',
            name='neighbor',
        ),
    ]
