# Generated by Django 4.0.3 on 2022-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0021_listofbooks_crank'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofbooks',
            name='occurence',
            field=models.IntegerField(default='0'),
        ),
    ]
